# File: devops_tools/momo/deployment.yaml
# K8s manifests for the Moment In Motion application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-deployment
  namespace: momo # Target namespace
  labels:
    app: momo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: momo
  template:
    metadata:
      labels:
        app: momo
    spec:
      containers:
      - name: momo-app
        # Pulling the application image from GHCR
        image: ghcr.io/brar-karamjit/momentinmotion:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000 
        env:
        - name: HELLO_SERVICE_URL
          value: "http://hello-service.hello.svc.cluster.local"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: momo-secrets
              key: django-secret-key
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: momo-secrets
              key: gemini-api-key
        - name: DJANGO_DEBUG
          value: "False"
        - name: DJANGO_ALLOWED_HOSTS
          value: "k8s.karamjitbrar.com"
        - name: DJANGO_FORCE_SCRIPT_NAME
          value: "/momo"
---
apiVersion: v1
kind: Service
metadata:
  name: momo-service
  namespace: momo # Target namespace
spec:
  selector:
    app: momo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
#Ingress Resource for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: momo-ingress
  namespace: momo 
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx 
  rules:
  - host: k8s.karamjitbrar.com # The host for the Ingress
    http:
      paths:
      - path: /momo(/|$)(.*) # The path for the Ingress
        pathType: Prefix
        backend:
          service:
            name: momo-service 
            port:
              number: 80
  tls:
  - secretName: k8s-tls
    hosts:
    - k8s.karamjitbrar.com