controller:
  hostNetwork: true

  hostPort:
    # -- Enable 'hostPort'
    enabled: true
    ports:
      # -- 'hostPort' http port
      http: 80
      # -- 'hostPort' https port
      https: 443

  service:
    # Set to ClusterIP as the main traffic is expected to hit the Node directly
    # via the HostPort configuration above.
    type: ClusterIP

  reportNodeInternalIp: true

  # Use the custom 404 error backend for all unmatched routes
  extraArgs:
    default-backend-service: "error-page/custom-error-backend"

